#!/bin/bash

getName () {
if [ -z "$1" ]; then
   local INFO=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused) | .name + " " + .output')
   read NAME OUT <<< "${INFO}"

   local LIST=`i3-msg -t get_tree | \
   jq --arg active_ws $NAME --arg active_output $OUT -r \
   '.nodes | .[] | select(.name==$active_output) | .nodes | .[] | select(.name=="content") | .nodes | .[] | \
   select(.name==$active_ws) | recurse(.nodes[]) | select(.window) | .name + " (\(.id))"'`
else
   local LIST=`i3-msg -t get_tree | \
   jq -r \
   '.nodes | .[] | select(.name!="__i3") | .nodes | .[] | \
   select(.name=="content") | recurse(.nodes[]) | select(.window) | .name + " (\(.id))"'`
fi
dmenu -l 20 -i -b <<< "${LIST}"
}

changeFocus () {
local WNAME=`getName $1`
if [ ! -z "$WNAME" ] ; then
   local CID=`sed "s/.*(\([0-9]*\))$/\1/" <<< "${WNAME}"`
   i3-msg [ con_id=$CID ] focus
fi
}

changeFocus $1
